#!/usr/bin/env python3
"""crow-draft — Draft agent v0: builds work packs for the top research picks.

Zero-cost, deterministic, stdlib-only. Reads opportunities.json, ranks with
research.fit_score, writes drafts/NN-slug.md plus drafts/index.json for the
dashboard. Runs daily on GitHub Actions after research.py.
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from research import fit_score, next_step, rationale

TOP_N = 5


def slugify(t):
    return re.sub(r"[^a-z0-9]+", "-", (t or "").lower()).strip("-")[:60] or "untitled"


def kind(o):
    t = (o.get("title") or "").lower()
    typ = (o.get("type") or "").lower()
    if any(w in t for w in ("video", "content", "twitter", "thread")):
        return "content"
    if any(w in t for w in ("deep dive", "research", "report", "write")):
        return "writing"
    if any(w in t for w in ("infographic", "design", "merchandise")):
        return "design"
    if "hackathon" in typ or "build" in t or "challenge" in t:
        return "build"
    return "generic"


SKELETONS = {
    "content": """## Script skeleton
- Hook (0–5s): the one line that stops the scroll
- Context (5–20s): why this matters right now
- Three beats: [point 1] / [point 2] / [point 3]
- CTA (last 5s): what the viewer should do

## Production checklist
- [ ] Collect required brand assets / logos / rule links from the listing
- [ ] Confirm format (vertical? length? platform?) and required tags/handles
- [ ] Draft shot list; record; edit; captions
- [ ] Post + submit link per listing instructions""",
    "writing": """## Outline
1. Executive summary (write last)
2. Landscape: key players, numbers, recent moves
3. Data: 3–5 primary sources with citations
4. Analysis: what the data actually says
5. Recommendations / takeaways

## Source list starters
- Official government / protocol / foundation reports
- Recent funding and ecosystem announcements
- On-chain or market data where relevant

## Time estimate
- Research: ~3h · Draft: ~3h · Edit + format: ~1h""",
    "design": """## Concept brief
- Core message the visual must communicate
- Content inventory: every fact/label that must appear
- Style: match sponsor brand kit if provided

## Production checklist
- [ ] Pull brand kit / colors / logos from listing
- [ ] Wireframe layout on paper first
- [ ] Produce in required format + export specs (px, format, bleed)
- [ ] Submit per listing instructions""",
    "build": """## MVP scope — one feature done well
- The single user story to demo:
- Stack (fastest path):
- What to fake/stub vs build for real:

## Judging-criteria mapping
- [ ] List each judging criterion from the rules
- [ ] One sentence per criterion on how the MVP addresses it

## Submission checklist
- [ ] Public repo with README (what/why/how to run)
- [ ] Demo video (2–3 min, show the happy path)
- [ ] Submit before deadline with all required fields""",
    "generic": """## Capture pass
- [ ] Full rules, eligibility (region/KYC/team), deadline (UTC)
- [ ] Deliverable format and submission channel
- [ ] Payout terms and method

## Go/no-go
- Effort estimate (hours):
- Realistic win probability:
- Decision:""",
}


def pack(i, o, now):
    days = o.get("days_left")
    deadline = "no deadline listed" if days is None else f"{round(days)} days left"
    return f"""# Draft pack — {o['title']}

- Listing: {o['url']}
- Value: ${o.get('value_usd') or 0:,.0f} {o.get('token', 'USD')}
- Deadline: {deadline} (as of {now})
- Fit score: {fit_score(o):,.0f} — {rationale(o)}
- First action: {next_step(o)}

## Go/no-go checklist
- [ ] Read full rules & eligibility (region, KYC, team size)
- [ ] Confirm submission format & judging criteria
- [ ] Note exact deadline (UTC)
- [ ] Confirm payout method matches operator wallets
- [ ] Estimate hours vs value — still worth it?

{SKELETONS[kind(o)]}

---
Generated by draft.py (Draft agent v0) — deterministic, no LLM. Refine by hand or with a local model.
"""


def main():
    opps = json.loads(Path("opportunities.json").read_text())
    top = sorted(opps, key=fit_score, reverse=True)[:TOP_N]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    out = Path("drafts")
    out.mkdir(exist_ok=True)
    for old in out.glob("*.md"):
        old.unlink()

    index = []
    for i, o in enumerate(top, 1):
        name = f"{i:02d}-{slugify(o['title'])}.md"
        (out / name).write_text(pack(i, o, now))
        index.append({
            "file": f"drafts/{name}",
            "title": o["title"],
            "url": o["url"],
            "value_usd": o.get("value_usd") or 0,
            "token": o.get("token", "USD"),
            "fit": fit_score(o),
            "kind": kind(o),
            "days_left": o.get("days_left"),
        })

    (out / "index.json").write_text(json.dumps(index, indent=1))
    print(f"{len(index)} draft packs -> drafts/")


if __name__ == "__main__":
    main()
